spring.application.name=healthops-auth-service
spring.sql.init.mode=always

spring.datasource.url=jdbc:postgresql://db:5432/healthops
spring.datasource.username=postgres
spring.datasource.password=postgres

server.port=4005