services:
  app:
    build: .
    container_name: analytics-service
    ports:
      - "4002:4002"
    networks:
      - internal
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

networks:
  internal:
    external: true
    name: microservices-network